#!/bin/bash

# List of Commands

#### Preprocessing commands ####



#### TZA ####
### Building disaggregation


### WorldPop - trained with coarse census data (adj.)


### MRF (adj.)


### ScaleNet - one country - coarse (& adj.)
# laplaceNLL, fold 0
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs 0 -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm m --loss NormL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold ${rs} -rs 0 -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold ${rs} -rs 0 -mm m --loss mse --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000

# in paper
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_${rs}_1,LogL1_c_new_${rs}_2,LogL1_c_new_${rs}_3,LogL1_c_new_${rs}_4,LogL1_c_new_${rs}_5

# in paper, single runs
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_single_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_single_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 50000 --name LogL1_c_new_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_${rs}_1,LogL1_c_new_${rs}_2,LogL1_c_new_${rs}_3,LogL1_c_new_single_${rs}_4,LogL1_c_new_single_${rs}_5


# coarse tza ablations, baselined
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_ooo_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_ooo_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_ooo_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_ooo_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_ooo_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss l1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_ooo_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_ab_ooo_${rs}_1,LogL1_c_new_ab_ooo_${rs}_2,LogL1_c_new_ab_ooo_${rs}_3,LogL1_c_new_ab_ooo_${rs}_4,LogL1_c_new_ab_ooo_${rs}_5

# coarse tza ablations, xoo
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xoo_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xoo_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xoo_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xoo_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xoo_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss LogL1 --admin_augment False --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xoo_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_ab_xoo_${rs}_1,LogL1_c_new_ab_xoo_${rs}_2,LogL1_c_new_ab_xoo_${rs}_3,LogL1_c_new_ab_xoo_${rs}_4,LogL1_c_new_ab_xoo_${rs}_5

# coarse tza ablations, oxo
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oxo_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oxo_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oxo_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oxo_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oxo_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss l1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oxo_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_ab_oxo_${rs}_1,LogL1_c_new_ab_oxo_${rs}_2,LogL1_c_new_ab_oxo_${rs}_3,LogL1_c_new_ab_oxo_${rs}_4,LogL1_c_new_ab_oxo_${rs}_5

# coarse tza ablations, oox
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_ab_oox_${rs}_1,LogL1_c_new_ab_oox_${rs}_2,LogL1_c_new_ab_oox_${rs}_3,LogL1_c_new_ab_oox_${rs}_4,LogL1_c_new_ab_oox_${rs}_5


# coarse tza ablations, oox, singles
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_singles_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_singles_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_oox_singles2_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_ab_oox_${rs}_1,LogL1_c_new_ab_oox_${rs}_2,LogL1_c_new_ab_oox_${rs}_3,LogL1_c_new_ab_oox_singles_${rs}_4,LogL1_c_new_ab_oox_singles_${rs}_5

# coarse tza ablations, oox, singles, long
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name LogL1_c_new_ab_oox_long_singles_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name LogL1_c_new_ab_oox_long_singles_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name LogL1_c_new_ab_oox_long_singles_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name LogL1_c_new_ab_oox_long_singles_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name LogL1_c_new_ab_oox_long_singles_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name LogL1_c_new_ab_oox_long_singles_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_ab_oox_long_singles_${rs}_1,LogL1_c_new_ab_oox_long_singles_${rs}_2,LogL1_c_new_ab_oox_long_singles_${rs}_3,LogL1_c_new_ab_oox_long_singles_singles_${rs}_4,LogL1_c_new_ab_oox_long_singles_singles_${rs}_5


# coarse tza ablations, oox, singles, cont
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --load_state LogL1_c_new_ab_oox_${rs}_1 --name LogL1_c_new_ab_oox_cont_singles_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --load_state LogL1_c_new_ab_oox_${rs}_2 --name LogL1_c_new_ab_oox_cont_singles_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --load_state LogL1_c_new_ab_oox_${rs}_3 --name LogL1_c_new_ab_oox_cont_singles_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --load_state LogL1_c_new_ab_oox_singles_${rs}_4 --name LogL1_c_new_ab_oox_cont_singles_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --load_state LogL1_c_new_ab_oox_singles_${rs}_5 --name LogL1_c_new_ab_oox_cont_singles_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss l1 --admin_augment True --population_target True --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name LogL1_c_new_ab_oox_cont_singles_v1_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_ab_oox_cont_singles_${rs}_1,LogL1_c_new_ab_oox_cont_singles_${rs}_2,LogL1_c_new_ab_oox_cont_singles_${rs}_3,LogL1_c_new_ab_oox_cont_singles_${rs}_4,LogL1_c_new_ab_oox_cont_singles_${rs}_5


# coarse tza ablations, xxo
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xxo_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xxo_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xxo_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xxo_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xxo_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss LogL1 --admin_augment False --population_target False --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new_ab_xxo_${rs}_X --e5f_metric best_mape -e5f LogL1_c_new_ab_xxo_${rs}_1,LogL1_c_new_ab_xxo_${rs}_2,LogL1_c_new_ab_xxo_${rs}_3,LogL1_c_new_ab_xxo_${rs}_4,LogL1_c_new_ab_xxo_${rs}_5




# all coarse, ac
python superpixel_disagg_model.py -train tza -train_lvl ac -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs 1610 -rsf 1610 -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_ac_1610_1
python superpixel_disagg_model.py -train tza -train_lvl ac -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_ac_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl ac -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_ac_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl ac -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_ac_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl ac -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_ac_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl ac -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_ac_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl ac -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_ac_${rs}_X --e5f_metric best_mape_adj -e5f LogL1_ac_${rs}_1,LogL1_ac_${rs}_2,LogL1_ac_${rs}_3,LogL1_ac_${rs}_4,LogL1_ac_${rs}_5


#l1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name l1_c_${rs}_1
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name l1_c_${rs}_2
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name l1_c_${rs}_3
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name l1_c_${rs}_4
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name l1_c_${rs}_5
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name l1_c_${rs}_X --e5f_metric best_mape -e5f l1_c_${rs}_1,l1_c_${rs}_2,l1_c_${rs}_3,l1_c_${rs}_4,l1_c_${rs}_5



# LogL1, k3111, coarse
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,1,1,1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_1_k3111
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,1,1,1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_2_k3111
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,1,1,1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_3_k3111
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,1,1,1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_4_k3111
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,1,1,1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_5_k3111
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,1,1,1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_X_k3111 --e5f_metric best_mape -e5f LogL1_c_new${rs}_1_k3111,LogL1_c_new${rs}_2_k3111,LogL1_c_new${rs}_3_k3111,LogL1_c_new${rs}_4_k3111,LogL1_c_new${rs}_5_k3111


# LogL1, Nathan Jacobas k3333, coarse
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_1_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_2_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_3_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_4_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_5_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name LogL1_c_new${rs}_X_k3333nj --e5f_metric best_mape -e5f LogL1_c_new${rs}_1_k3333nj,LogL1_c_new${rs}_2_k3333nj,LogL1_c_new${rs}_3_k3333nj,LogL1_c_new${rs}_4_k3333nj,LogL1_c_new${rs}_5_k3333nj



### ScaleNet - one country - fine (& adj.)
# laplaceNLL, fold 0
#a
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_1a
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_2a
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_3a
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_4a
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_5a
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm d --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 100000 --e5f_metric best_mape -e5f laplace_f_${rs}_1a,laplace_f_${rs}_2a,laplace_f_${rs}_3a,laplace_f_${rs}_4a,laplace_f_${rs}_5a

# laplaceNLL, b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_1b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_2b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_3b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_4b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_5b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm d --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 100000 --e5f_metric best_mape -e5f laplace_f_${rs}_1b,laplace_f_${rs}_2b,laplace_f_${rs}_3b,laplace_f_${rs}_4b,laplace_f_${rs}_5b

# laplaceNLL, al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_1al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_2al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_3al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_4al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name laplace_f_${rs}_5al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm d --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 100000 --e5f_metric best_mape -e5f laplace_f_${rs}_1al,laplace_f_${rs}_2al,laplace_f_${rs}_3al,laplace_f_${rs}_4al,laplace_f_${rs}_5al

# mse
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm m --loss mse --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name mse_f_${rs}_1al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -mm m --loss mse --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name mse_f_${rs}_2al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -mm m --loss mse --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name mse_f_${rs}_3al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -mm m --loss mse --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name mse_f_${rs}_4al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -mm m --loss mse --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name mse_f_${rs}_5al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm d --loss mse --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 100000 --e5f_metric best_mape -e5f mse_f_${rs}_1al,mse_f_${rs}_2al,mse_f_${rs}_3al,mse_f_${rs}_4al,mse_f_${rs}_5al

# LogL1
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 100000 --name LogL1_f_${rs}_Xal --e5f_metric best_mape -e5f LogL1_f_${rs}_1al,LogL1_f_${rs}_2al,LogL1_f_${rs}_3al,LogL1_f_${rs}_4al,LogL1_f_${rs}_5al

# LogL2
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm m --loss LogL2 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL2_f_${rs}_1al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -mm m --loss LogL2 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL2_f_${rs}_2al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -mm m --loss LogL2 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL2_f_${rs}_3al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -mm m --loss LogL2 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL2_f_${rs}_4al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -mm m --loss LogL2 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL2_f_${rs}_5al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm d --loss LogL2 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 100000 --name LogL2_f_${rs}_Xal --e5f_metric best_mape -e5f LogL2_f_${rs}_1al,LogL2_f_${rs}_2al,LogL2_f_${rs}_3al,LogL2_f_${rs}_4al,LogL2_f_${rs}_5al

# l1
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name l1_f_${rs}_1al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name l1_f_${rs}_2al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name l1_f_${rs}_3al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name l1_f_${rs}_4al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name l1_f_${rs}_5al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm d --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 100000 --name l1_f_${rs}_Xal --e5f_metric best_mape -e5f l1_f_${rs}_1al,l1_f_${rs}_2al,l1_f_${rs}_3al,l1_f_${rs}_4al,l1_f_${rs}_5al

# gaussNLL, al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss gaussNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name gaussNLL_f_${rs}_1al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs 1610 -rsf 1610 -mm m --loss gaussNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name gaussNLL_f_1610_1al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss gaussNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name gaussNLL_f_${rs}_2al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss gaussNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name gaussNLL_f_${rs}_3al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss gaussNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name gaussNLL_f_${rs}_4al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss gaussNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name gaussNLL_f_${rs}_5al
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -mm d --loss gaussNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 100000 --e5f_metric best_mape -e5f gaussNLL_f_${rs}_1al,gaussNLL_f_${rs}_2al,gaussNLL_f_${rs}_3al,gaussNLL_f_${rs}_4al,gaussNLL_f_${rs}_5al

# Kernel size kernel_size 3333
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k3333
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k3333
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k3333
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k3333
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k3333
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k3333 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k3333,LogL1_f_${rs}_2_k3333,LogL1_f_${rs}_3_k3333,LogL1_f_${rs}_4_k3333,LogL1_f_${rs}_5_k3333

# Kernel size kernel_size 5555
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k5555
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k5555
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k5555
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k5555
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k5555
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k5555 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k5555,LogL1_f_${rs}_2_k5555,LogL1_f_${rs}_3_k5555,LogL1_f_${rs}_4_k5555,LogL1_f_${rs}_5_k5555

# Kernel size kernel_size 5555b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.00001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k5555b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.00001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k5555b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.00001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k5555b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.00001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k5555b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.00001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k5555b
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.00001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k5555b --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k5555b,LogL1_f_${rs}_2_k5555b,LogL1_f_${rs}_3_k5555b,LogL1_f_${rs}_4_k5555b,LogL1_f_${rs}_5_k5555b

# Kernel size kernel_size 3111
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k3111
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k3111
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k3111
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k3111
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k3111
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k3111 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k3111,LogL1_f_${rs}_2_k3111,LogL1_f_${rs}_3_k3111,LogL1_f_${rs}_4_k3111,LogL1_f_${rs}_5_k3111


# nathan Jacobs
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k3333nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k3333nj --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k3333nj,LogL1_f_${rs}_2_k3333nj,LogL1_f_${rs}_3_k3333nj,LogL1_f_${rs}_4_k3333nj,LogL1_f_${rs}_5_k3333nj


# no aug
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target False --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target False --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target False --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target False --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target False --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target False --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k1111nj --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k1111nj,LogL1_f_${rs}_2_k1111nj,LogL1_f_${rs}_3_k1111nj,LogL1_f_${rs}_4_k1111nj,LogL1_f_${rs}_5_k1111nj

# no scale
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment True --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment True --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment True --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment True --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment True --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k1111nj
python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 1,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment True --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k1111nj --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k1111nj,LogL1_f_${rs}_2_k1111nj,LogL1_f_${rs}_3_k1111nj,LogL1_f_${rs}_4_k1111nj,LogL1_f_${rs}_5_k1111nj





### ScaleNet - multi country - fine (& adj.)
# laplaceNLL, fold 0
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs}  -mm m,m,m,m,m,m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_laplace_${rs}_1
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs}  -mm m,m,m,m,m,m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_laplace_${rs}_2
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs}  -mm m,m,m,m,m,m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_laplace_${rs}_3
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs}  -mm m,m,m,m,m,m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_laplace_${rs}_4
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs}  -mm m,m,m,m,m,m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_laplace_${rs}_5
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs}  -mm m,m,m,m,m,m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_laplace_${rs}_X --e5f_metric best_mape -e5f multi_laplace_${rs}_1,multi_laplace_${rs}_2,multi_laplace_${rs}_3,multi_laplace_${rs}_4,multi_laplace_${rs}_5

# LogL1, fold 0
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_1
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_2
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_3
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_4
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_5
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_X --e5f_metric best_mape -e5f multi_LogL1_${rs}_1,multi_LogL1_${rs}_2,multi_LogL1_${rs}_3,multi_LogL1_${rs}_4,multi_LogL1_${rs}_5

# LogL1, fold 0, lr small
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.00001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_1s
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.00001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_2s
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.00001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_3s
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.00001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_4s
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.00001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_5s
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.00001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_X --e5f_metric best_mape -e5f multi_LogL1_${rs}_1s,multi_LogL1_${rs}_2s,multi_LogL1_${rs}_3s,multi_LogL1_${rs}_4s,multi_LogL1_${rs}_5s

# LogL1, fold 0, lr large
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_1l
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_2l
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_3l
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_4l
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_5l
python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 5000 --validation_fold 0 -rs ${rs} -mm m,m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 210000 --name multi_LogL1_${rs}_X --e5f_metric best_mape -e5f multi_LogL1_${rs}_1l,multi_LogL1_${rs}_2l,multi_LogL1_${rs}_3l,multi_LogL1_${rs}_4l,multi_LogL1_${rs}_5l

# Withdropout
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 20000 --dropout 0.4 --name transfer_LogL1_${rs}_1do
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 20000 --dropout 0.4 --name transfer_LogL1_${rs}_2do
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 20000 --dropout 0.4 --name transfer_LogL1_${rs}_3do
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 20000 --dropout 0.4 --name transfer_LogL1_${rs}_4do
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 20000 --dropout 0.4 --name transfer_LogL1_${rs}_5do
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test tza,uga,rwa,cod,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 20000 --dropout 0.4 --name transfer_LogL1_${rs}_Xdo --e5f_metric best_mape_avg -e5f transfer_LogL1_${rs}_1do,transfer_LogL1_${rs}_2do,transfer_LogL1_${rs}_3do,transfer_LogL1_${rs}_4do,transfer_LogL1_${rs}_5do

python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,cod,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs 1610 -rsf 1610 -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_LogL1_1610_1
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 1 -rs 1610 -rsf 1610 -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_LogL1_1611_2
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 2 -rs 1610 -rsf 1610 -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_LogL1_1612_3
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 3 -rs 1610 -rsf 1610 -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_LogL1_1613_4
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 4 -rs 1610 -rsf 1610 -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_LogL1_1614_5
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test tza,uga,rwa,cod,nga,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs 1610 -rsf 1610 -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_LogL1_1610_X --e5f_metric best_mape_avg -e5f transfer_LogL1_1610_1,transfer_LogL1_1610_2,transfer_LogL1_1610_3,transfer_LogL1_1610_4,transfer_LogL1_1610_5


### ScaleNet - transfer country - fine (& adj.)
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.01 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_tza_${rs} --full_ceval False 
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test tza -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_tza_${rs}_evaled --eval_model transfer_to_tza_${rs} --e5f_metric best_mape_avg

# tza, l1
 python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.01 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_tza_l1_${rs} --full_ceval False 
python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test tza -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_tza_l1_${rs}_evaled --eval_model transfer_to_tza_l1_${rs} --e5f_metric best_mape_avg
 
# to moz, in paper
python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 3.0 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_3_${rs} --full_ceval False 
python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.000001 -optim adam -wr 3.0 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_1_${rs}_evaled --eval_model transfer_to_moz_3_${rs} --e5f_metric best_mape_avg

# to moz, l1
python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 1.0 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_1_l1_${rs} --full_ceval False 
python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.000001 -optim adam -wr 1.0 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_1_l1_${rs}_evaled --eval_model transfer_to_moz_1_l1_${rs} --e5f_metric best_mape_avg

# to moz, more lr
python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.00001 -wr 1.0 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_1mlr_${rs} --full_ceval False 
python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.00001 -optim adam -wr 1.0 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_1mlr_${rs}_evaled --eval_model transfer_to_moz_1mlr_${rs} --e5f_metric best_mape_avg

# to moz, l1, more lr
python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.00001 -wr 1.0 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_1_l1_${rs} --full_ceval False 
python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.00001 -optim adam -wr 1.0 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_1mlr_l1_${rs}_evaled --eval_model transfer_to_moz_1mlr_l1_${rs} --e5f_metric best_mape_avg

# to rwa
python superpixel_disagg_model.py -train uga,moz,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.01 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_rwa_${rs} --full_ceval False 
python superpixel_disagg_model.py -train uga,moz,cod,nga,tza -train_lvl f,f,f,f,f -test rwa -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_rwa_${rs}_evaled --eval_model transfer_to_rwa_${rs} --e5f_metric best_mape_avg

# to uga
python superpixel_disagg_model.py -train rwa,moz,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.01 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_uga_${rs} --full_ceval False 
python superpixel_disagg_model.py -train rwa,moz,cod,nga,tza -train_lvl f,f,f,f,f -test uga -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_uga_${rs}_evaled --eval_model transfer_to_uga_${rs} --e5f_metric best_mape_avg


### Building Disaggregation - transfer country - fine (& adj.) 
python building_disagg_baseline.py --output_dir output_dir/ --train_dataset_name uga,moz,rwa --test_dataset_name tza --global_disag 
