!/bin/bash

#BSUB -W 50:00
#BSUB -n 1
#BSUB -o euleroutputs/outfile_%J.%I.txt
#BSUB -R "rusage[mem=90000,ngpus_excl_p=1]"
#BSUB -R "select[gpu_mtotal0>=9800]"
# ## ##BSUB -R "rusage[scratch=120000]"
#BSUB -J "rs[1-5]"

# job index (set this to your system job variable e.g. for parallel job arrays)
# used to set model_idx and test_fold_idx below.
#index=0   # index=0 --> model_idx=0, test_fold_idx=0
index=$((LSB_JOBINDEX))
rs=$(( ($index % 5)+1610 ))

leave=Clipart

# cp -r /scratch2/Code/stylebias/data/OfficeHome $TMPDIR/
# cp -r /cluster/work/igp_psr/nkalischek/stylebias/data/OfficeHome $TMPDIR/
#cp -r -v /cluster/work/igp_psr/metzgern/HAC/code/repocode/population_estimation/datasets $TMPDIR/

echo job index: $index
echo leave: $leave
echo val_fold: $rs
echo TEMPDIR: $TMPDIR

source HACenv/bin/activate

# load modules
module load gcc/8.2.0 gdal/3.2.0 zlib/1.2.9 eth_proxy hdf5/1.10.1


python superpixel_disagg_model.py -train moz -train_lvl ac -test moz -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name moz_ac_01${rs}_5
python superpixel_disagg_model.py -train moz -train_lvl ac -test moz -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name moz_ac_01${rs}_X --e5f_metric best_mape_adj -e5f moz_ac_01${rs}_1,moz_ac_01${rs}_2,moz_ac_01${rs}_3,moz_ac_01${rs}_4,moz_ac_01${rs}_5


#python superpixel_disagg_model.py -train cod -train_lvl f -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name cod_f_01_${rs}_5
#python superpixel_disagg_model.py -train cod -train_lvl f -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name cod_f_01_${rs}_X --e5f_metric best_mape -e5f cod_f_01_${rs}_1,cod_f_01_${rs}_2,cod_f_01_${rs}_3,cod_f_01_${rs}_4,cod_f_01_${rs}_5


#python superpixel_disagg_model.py -train cod -train_lvl f -test cod -lr 0.00001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name cod_f_1_${rs}_4
#python superpixel_disagg_model.py -train cod -train_lvl f -test cod -lr 0.00001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name cod_f_1_${rs}_5
#python superpixel_disagg_model.py -train cod -train_lvl f -test cod -lr 0.00001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name cod_f_1_${rs}_X --e5f_metric best_mape -e5f cod_f_1_${rs}_1,cod_f_1_${rs}_2,cod_f_1_${rs}_3,cod_f_1_${rs}_4,cod_f_1_${rs}_5


#python superpixel_disagg_model.py -train cod -train_lvl f -test cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name cod_f_${rs}_5
#python superpixel_disagg_model.py -train cod -train_lvl f -test cod -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name cod_f_${rs}_X --e5f_metric best_mape -e5f cod_f_${rs}_1,cod_f_${rs}_2,cod_f_${rs}_3,cod_f_${rs}_4,cod_f_${rs}_5


#https://scicomp.ethz.ch/wiki/Work_storage_/cluster/work/_partially_available_(10_May_2022)
#python superpixel_disagg_model.py -train moz -train_lvl ac -test moz -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name moz_ac_01${rs}_4
#python superpixel_disagg_model.py -train moz -train_lvl ac -test moz -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 101000 --name moz_ac_01${rs}_5
#python superpixel_disagg_model.py -train moz -train_lvl ac -test moz -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name moz_ac_01${rs}_X --e5f_metric best_mape_adj -e5f moz_ac_01${rs}_1,moz_ac_01${rs}_2,moz_ac_01${rs}_3,moz_ac_01${rs}_4,moz_ac_01${rs}_5

# rwa, ac
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 3.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_3_${rs}_1
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 3.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_3_${rs}_2
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 3.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_3_${rs}_3
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 3.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_3_${rs}_4
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 3.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_3_${rs}_5
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 3.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_3_${rs}_X --e5f_metric best_mape_adj -e5f rwa_ac_3_${rs}_1,rwa_ac_3_${rs}_2,rwa_ac_3_${rs}_3,rwa_ac_3_${rs}_4,rwa_ac_3_${rs}_5


# rwa, ac
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_1_${rs}_1
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_1_${rs}_2
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_1_${rs}_3
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_1_${rs}_4
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_1_${rs}_5
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_1_${rs}_X --e5f_metric best_mape_adj -e5f rwa_ac_1_${rs}_1,rwa_ac_1_${rs}_2,rwa_ac_1_${rs}_3,rwa_ac_1_${rs}_4,rwa_ac_1_${rs}_5


# rwa, ac
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_03_${rs}_1
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_03_${rs}_2
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_03_${rs}_3
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_03_${rs}_4
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_03_${rs}_5
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_03_${rs}_X --e5f_metric best_mape_adj -e5f rwa_ac_03_${rs}_1,rwa_ac_03_${rs}_2,rwa_ac_03_${rs}_3,rwa_ac_03_${rs}_4,rwa_ac_03_${rs}_5

# rwa, ac
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_01_${rs}_1
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_01_${rs}_2
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_01_${rs}_3
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_01_${rs}_4
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_01_${rs}_5
#python superpixel_disagg_model.py -train rwa -train_lvl ac -test rwa -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name rwa_ac_01_${rs}_X --e5f_metric best_mape_adj -e5f rwa_ac_01_${rs}_1,rwa_ac_01_${rs}_2,rwa_ac_01_${rs}_3,rwa_ac_01_${rs}_4,rwa_ac_01_${rs}_5



# cod
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_1_${rs}_1
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_1_${rs}_2
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_1_${rs}_3
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_1_${rs}_4
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_1_${rs}_5
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_1_${rs}_X --e5f_metric best_mape -e5f cod_c_1_${rs}_1,cod_c_1_${rs}_2,cod_c_1_${rs}_3,cod_c_1_${rs}_4,cod_c_1_${rs}_5

# cod
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_01_${rs}_1
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_01_${rs}_2
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_01_${rs}_3
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_01_${rs}_4
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_01_${rs}_5
#python superpixel_disagg_model.py -train cod -train_lvl c -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_c_01_${rs}_X --e5f_metric best_mape -e5f cod_c_01_${rs}_1,cod_c_01_${rs}_2,cod_c_01_${rs}_3,cod_c_01_${rs}_4,cod_c_01_${rs}_5




# cod, ac
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_1_${rs}_1
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_1_${rs}_2
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_1_${rs}_3
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_1_${rs}_4
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_1_${rs}_5
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 1.0 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_1_${rs}_X --e5f_metric best_mape_adj -e5f cod_ac_1_${rs}_1,cod_ac_1_${rs}_2,cod_ac_1_${rs}_3,cod_ac_1_${rs}_4,cod_ac_1_${rs}_5


# cod, ac
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_01_${rs}_1
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_01_${rs}_2
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_01_${rs}_3
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_01_${rs}_4
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_01_${rs}_5
#python superpixel_disagg_model.py -train cod -train_lvl ac -test cod -lr 0.0001 -optim adam -wr 0.1 --dropout 0.4 -adamwr 0. -lstep 400 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --full_ceval False --name cod_ac_01_${rs}_X --e5f_metric best_mape_adj -e5f cod_ac_01_${rs}_1,cod_ac_01_${rs}_2,cod_ac_01_${rs}_3,cod_ac_01_${rs}_4,cod_ac_01_${rs}_5

# to moz, l1
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 1.0 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_1_l1_${rs} --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.000001 -optim adam -wr 1.0 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_1_l1_${rs}_evaled --eval_model transfer_to_moz_1_l1_${rs} --e5f_metric best_mape_avg


# tza, l1
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.01 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_tza_l1_${rs} --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,moz -train_lvl f,f,f,f,f -test tza -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_tza_l1_${rs}_evaled --eval_model transfer_to_tza_l1_${rs} --e5f_metric best_mape_avg


# to moz
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 3.0 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_3_${rs} --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.000001 -optim adam -wr 3.0 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 50000 --name transfer_to_moz_1_${rs}_evaled --eval_model transfer_to_moz_3_${rs} --e5f_metric best_mape_avg

# to moz
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 3.0 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_3_${rs} --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.000001 -optim adam -wr 3.0 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_1_${rs}_evaled --eval_model transfer_to_moz_3_${rs} --e5f_metric best_mape_avg


# to moz
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 1.0 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_1_${rs} --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.000001 -optim adam -wr 1.0 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_1_${rs}_evaled --eval_model transfer_to_moz_1_${rs} --e5f_metric best_mape_avg


# Kernel size kernel_size 1111  moz, l1 fine
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam --kernel_size 1,1,1,1 -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_f_l1_${rs}_1
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam --kernel_size 1,1,1,1 -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_f_l1_${rs}_3
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam --kernel_size 1,1,1,1 -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_f_l1_${rs}_2
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam --kernel_size 1,1,1,1 -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_f_l1_${rs}_4
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam --kernel_size 1,1,1,1 -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_f_l1_${rs}_5
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam --kernel_size 1,1,1,1 -wr 0.3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_f_l1_${rs}_X --e5f_metric best_mape -e5f moz_f_l1_${rs}_1,moz_f_l1_${rs}_2,moz_f_l1_${rs}_3,moz_f_l1_${rs}_4,moz_f_l1_${rs}_5



#moz coarse, l1
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs 1610 -rsf 1610 -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_c_1610_1
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_c_l1_${rs}_1
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_c_l1_${rs}_2
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_c_l1_${rs}_3
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_c_l1_${rs}_4
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_c_l1_${rs}_5
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name moz_c_l1_${rs}_X --e5f_metric best_mape -e5f moz_c_l1_${rs}_1,moz_c_l1_${rs}_2,moz_c_l1_${rs}_3,moz_c_l1_${rs}_4,moz_c_l1_${rs}_5




# all countries, multicountry, no dropout, wr=0.1
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_1 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_2 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_4 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_5 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_3 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_X_uga --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test tza -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_X_tza --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test rwa -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_X_rwa --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test nga -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_X_nga --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test moz -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_X_moz --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_X_cod --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 100000 --name multi_01_${rs}_X_all --e5f_metric best_mape_avg -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5



# all countries, multicountry, no dropout, wr=0.1
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_1 --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_2 --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_4 --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_5 --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_3 --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_X_uga --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test tza -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_X_tza --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test rwa -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_X_rwa --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test nga -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_X_nga --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test moz -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_X_moz --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_X_cod --e5f_metric best_mape -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_01_${rs}_X_all --e5f_metric best_mape_avg -e5f multi_01_${rs}_1,multi_01_${rs}_2,multi_01_${rs}_3,multi_01_${rs}_4,multi_01_${rs}_5



# all countries, multicountry, no dropout
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_1 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_2 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_3 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_4 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_5 --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_X_uga --e5f_metric best_mape -e5f multi_${rs}_1,multi_${rs}_2,multi_${rs}_3,multi_${rs}_4,multi_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test tza -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_X_tza --e5f_metric best_mape -e5f multi_${rs}_1,multi_${rs}_2,multi_${rs}_3,multi_${rs}_4,multi_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test rwa -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_X_rwa --e5f_metric best_mape -e5f multi_${rs}_1,multi_${rs}_2,multi_${rs}_3,multi_${rs}_4,multi_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test nga -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_X_nga --e5f_metric best_mape -e5f multi_${rs}_1,multi_${rs}_2,multi_${rs}_3,multi_${rs}_4,multi_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test moz -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_X_moz --e5f_metric best_mape -e5f multi_${rs}_1,multi_${rs}_2,multi_${rs}_3,multi_${rs}_4,multi_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test cod -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_X_cod --e5f_metric best_mape -e5f multi_${rs}_1,multi_${rs}_2,multi_${rs}_3,multi_${rs}_4,multi_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga,rwa,tza,nga,moz,cod -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_${rs}_X_all --e5f_metric best_mape_avg -e5f multi_${rs}_1,multi_${rs}_2,multi_${rs}_3,multi_${rs}_4,multi_${rs}_5


#moz coarse mod k3333, nj, fine
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_f_${rs}_k3333nj_1
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_f_${rs}_k3333nj_2
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_f_${rs}_k3333nj_3
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_f_${rs}_k3333nj_4
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_f_${rs}_k3333nj_5
#python superpixel_disagg_model.py -train moz -train_lvl f -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_f_${rs}_k3333nj_X --e5f_metric best_mape -e5f 03moz_f_${rs}_k3333nj_1,03moz_f_${rs}_k3333nj_2,03moz_f_${rs}_k3333nj_3,03moz_f_${rs}_k3333nj_4,03moz_f_${rs}_k3333nj_5

#moz coarse mod k3333, nj
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_c_${rs}_k3333nj_1
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_c_${rs}_k3333nj_2
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_c_${rs}_k3333nj_3
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_c_${rs}_k3333nj_4
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_c_${rs}_k3333nj_5
#python superpixel_disagg_model.py -train moz -train_lvl c -test moz -lr 0.00001 -optim adam -wr 0.3 --kernel_size 3,3,3,3 --dropout 0.4 -adamwr 0. -lstep 200 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --admin_augment False --population_target True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name 03moz_c_${rs}_k3333nj_X --e5f_metric best_mape -e5f 03moz_c_${rs}_k3333nj_1,03moz_c_${rs}_k3333nj_2,03moz_c_${rs}_k3333nj_3,03moz_c_${rs}_k3333nj_4,03moz_c_${rs}_k3333nj_5

# to rwa
#python superpixel_disagg_model.py -train uga,moz,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.01 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_rwa_${rs} --full_ceval False
#python superpixel_disagg_model.py -train uga,moz,cod,nga,tza -train_lvl f,f,f,f,f -test rwa -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_rwa_${rs}_evaled --eval_model transfer_to_rwa_${rs} --e5f_metric best_mape_avg

# uga, multicountry, no dropout
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_ndo_uga_c_${rs}_1
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_ndo_uga_c_${rs}_2
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_ndo_uga_c_${rs}_3
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_ndo_uga_c_${rs}_4
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_ndo_uga_c_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_ndo_uga_c_${rs}_X --e5f_metric best_mape -e5f multi_ndo_uga_c_${rs}_1,multi_ndo_uga_c_${rs}_2,multi_ndo_uga_c_${rs}_3,multi_ndo_uga_c_${rs}_4,multi_ndo_uga_c_${rs}_5

# uga, multicountry
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_1
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_2
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_3
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_4
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_X --e5f_metric best_mape -e5f multi_uga_c_${rs}_1,multi_uga_c_${rs}_2,multi_uga_c_${rs}_3,multi_uga_c_${rs}_4,multi_uga_c_${rs}_5


# uga, multicountry
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_1
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_2
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_3
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_4
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_5
#python superpixel_disagg_model.py -train uga,rwa,tza,nga,moz,cod  -train_lvl f,f,f,f,f,f -test uga -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name multi_uga_c_${rs}_X --e5f_metric best_mape -e5f multi_uga_c_${rs}_1,multi_uga_c_${rs}_2,multi_uga_c_${rs}_3,multi_uga_c_${rs}_4,multi_uga_c_${rs}_5


# to moz
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.3 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_03_${rs} --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.000001 -optim adam -wr 0.3 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_03_${rs}_evaled --eval_model transfer_to_moz_03_${rs} --e5f_metric best_mape_avg


# to moz
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.1 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_01_${rs} --full_ceval False
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.000001 -optim adam -wr 0.1 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_01_${rs}_evaled --eval_model transfer_to_moz_01_${rs} --e5f_metric best_mape_avg


# to uga
#python superpixel_disagg_model.py -train rwa,moz,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.01 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_uga_${rs} --full_ceval False
#python superpixel_disagg_model.py -train rwa,moz,cod,nga,tza -train_lvl f,f,f,f,f -test uga -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_uga_${rs}_evaled --eval_model transfer_to_uga_${rs} --e5f_metric best_mape_avg


# to moz
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test uga,rwa,nga,moz,cod,tza -lr 0.000001 -wr 0.01 -optim adam -adamwr 0 -lstep 800 --validation_split 0.2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_${rs} --full_ceval False 
#python superpixel_disagg_model.py -train uga,rwa,cod,nga,tza -train_lvl f,f,f,f,f -test moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --max_step 30000 --name transfer_to_moz_${rs}_evaled --eval_model transfer_to_moz_${rs} --e5f_metric best_mape_avg


#python superpixel_disagg_model.py -train tza -train_lvl c -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss l1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 50000 --name l1_c_${rs}_X --e5f_metric best_mape -e5f l1_c_${rs}_1,l1_c_${rs}_2,l1_c_${rs}_3,l1_c_${rs}_4,l1_c_${rs}_5

# # Kernel size kernel_size 3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k3333 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k3333,LogL1_f_${rs}_2_k3333,LogL1_f_${rs}_3_k3333,LogL1_f_${rs}_4_k3333,LogL1_f_${rs}_5_k3333

# # Kernel size kernel_size 5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k5555
#p#ython superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k5555 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k5555,LogL1_f_${rs}_2_k5555,LogL1_f_${rs}_3_k5555,LogL1_f_${rs}_4_k5555,LogL1_f_${rs}_5_k5555

# # Kernel size kernel_size 5555b
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k5555b
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k5555b
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k5555b
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k5555b
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k5555b
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k5555b --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k5555b,LogL1_f_${rs}_2_k5555b,LogL1_f_${rs}_3_k5555b,LogL1_f_${rs}_4_k5555b,LogL1_f_${rs}_5_k5555b

# # Kernel size kernel_size 3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k3111 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k3111,LogL1_f_${rs}_2_k3111,LogL1_f_${rs}_3_k3111,LogL1_f_${rs}_4_k3111,LogL1_f_${rs}_5_k3111






# Kernel size kernel_size 3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k3111 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k3111,LogL1_f_${rs}_2_k3111,LogL1_f_${rs}_3_k3111,LogL1_f_${rs}_4_k3111,LogL1_f_${rs}_5_k3111


# Kernel size kernel_size 5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k5555 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k5555,LogL1_f_${rs}_2_k5555,LogL1_f_${rs}_3_k5555,LogL1_f_${rs}_4_k5555,LogL1_f_${rs}_5_k5555


# Kernel size kernel_size 3333
#:wqpython superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k3333 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k3333,LogL1_f_${rs}_2_k3333,LogL1_f_${rs}_3_k3333,LogL1_f_${rs}_4_k3333,LogL1_f_${rs}_5_k3333


# Kernel size kernel_size 3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k3111
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,1,1,1 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k3111 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k3111,LogL1_f_${rs}_2_k3111,LogL1_f_${rs}_3_k3111,LogL1_f_${rs}_4_k3111,LogL1_f_${rs}_5_k3111

# Kernel size kernel_size 5555
#3#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k5555
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 5,5,5,5 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k5555 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k5555,LogL1_f_${rs}_2_k5555,LogL1_f_${rs}_3_k5555,LogL1_f_${rs}_4_k5555,LogL1_f_${rs}_5_k5555


# Kernel size kernel_size 3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_1_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_2_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_3_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_4_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_5_k3333
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam --kernel_size 3,3,3,3 -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMDIR/datasets --sampler custom --max_step 150000 --name LogL1_f_${rs}_X_k3333 --e5f_metric best_mape -e5f LogL1_f_${rs}_1_k3333,LogL1_f_${rs}_2_k3333,LogL1_f_${rs}_3_k3333,LogL1_f_${rs}_4_k3333,LogL1_f_${rs}_5_k3333


### ScaleNet - one country - fine (& adj.)
# laplaceNLL, fold 0
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs 0 -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 -name laplace_f_${rs}_1
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 1 -rs 0 -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 -name laplace_f_${rs}_2
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 2 -rs 0 -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 -name laplace_f_${rs}_3
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 3 -rs 0 -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 -name laplace_f_${rs}_4
#python superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 4 -rs 0 -mm m --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 150000 -name laplace_f_${rs}_5
#ipython superpixel_disagg_model.py -train tza -train_lvl f -test tza -lr 0.0001 -optim adam -wr 0.01 --dropout 0.4 -adamwr 0. -lstep 800 --validation_fold 0 -rs 0 -mm d --loss laplaceNLL --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --sampler custom --max_step 100000 --e5f_metric best_mape -e5f laplace_f_${rs}_1,laplace_f_${rs}_2,laplace_f_${rs}_3,laplace_f_${rs}_4,laplace_f_${rs}_5

# without NGA
# python superpixel_disagg_model.py -train uga,rwa,cod,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 30000 --name transfer_LogL1_${rs}_1n
# python superpixel_disagg_model.py -train uga,rwa,cod,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 1 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 30000 --name transfer_LogL1_${rs}_2n
# python superpixel_disagg_model.py -train uga,rwa,cod,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 2 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 30000 --name transfer_LogL1_${rs}_3n
# python superpixel_disagg_model.py -train uga,rwa,cod,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 3 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 30000 --name transfer_LogL1_${rs}_4n
# python superpixel_disagg_model.py -train uga,rwa,cod,moz -train_lvl f,f,f,f,f -test uga,rwa,moz,cod,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 4 -rs ${rs} -rsf ${rs} -mm m,m,m,m,m --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 30000 --name transfer_LogL1_${rs}_5n
# python superpixel_disagg_model.py -train uga,rwa,cod,moz -train_lvl f,f,f,f,f -test tza,uga,rwa,cod,moz -lr 0.000001 -optim adam -wr 0.01 -adamwr 0. -lstep 800 --validation_fold 0 -rs ${rs} -rsf ${rs} -mm d,d,d,d,d --loss LogL1 --input_scaling True --output_scaling True --silent_mode True --dataset_dir $TMPDIR/datasets --max_step 30000 --name transfer_LogL1_${rs}_Xn --e5f_metric best_mape_avg -e5f transfer_LogL1_${rs}_1n,transfer_LogL1_${rs}_2n,transfer_LogL1_${rs}_3n,transfer_LogL1_${rs}_4n,transfer_LogL1_${rs}_5n

